config_query = f"""
        DECLARE @APP_WEB_STOCK_1_COLOR NVARCHAR(20)
        DECLARE @APP_WEB_STOCK_1_LEYENDA NVARCHAR(20)
        DECLARE @APP_WEB_STOCK_1_PORCENTAJE NVARCHAR(20)
        DECLARE @APP_WEB_STOCK_1_CONDICION NVARCHAR(20)
        DECLARE @APP_WEB_STOCK_1_TIPO_STOCK NVARCHAR(20)

        DECLARE @APP_WEB_STOCK_2_COLOR NVARCHAR(20)
        DECLARE @APP_WEB_STOCK_2_LEYENDA NVARCHAR(20)
        DECLARE @APP_WEB_STOCK_2_PORCENTAJE NVARCHAR(20)
        DECLARE @APP_WEB_STOCK_2_CONDICION NVARCHAR(20)
        DECLARE @APP_WEB_STOCK_2_TIPO_STOCK NVARCHAR(20)

        DECLARE @APP_WEB_STOCK_3_COLOR NVARCHAR(20)
        DECLARE @APP_WEB_STOCK_3_LEYENDA NVARCHAR(20)
        DECLARE @APP_WEB_STOCK_3_PORCENTAJE NVARCHAR(20)
        DECLARE @APP_WEB_STOCK_3_CONDICION NVARCHAR(20)
        DECLARE @APP_WEB_STOCK_3_TIPO_STOCK NVARCHAR(20)

        DECLARE @APP_WEB_USA_SEMAFORO_STOCK NVARCHAR(2)

        DECLARE @APP_WEB_COMENTARIOS_DASHBOARD NVARCHAR(MAX)

        DECLARE @APP_WEB_TC_DEFAULT_CARRO NVARCHAR(4)
        DECLARE @APP_WEB_TC_DEFAULT_FACTURADOR NVARCHAR(4)
        DECLARE @APP_WEB_TC_DEFAULT_FACTURADORG NVARCHAR(4)

        DECLARE @APP_WEB_BRANCH_DEFAULT_NP NVARCHAR(4)
        DECLARE @APP_WEB_BRANCH_DEFAULT_FP NVARCHAR(4)
        DECLARE @APP_WEB_BRANCH_DEFAULT_FC NVARCHAR(4)

        DECLARE @APP_WEB_FORCE_BRANCH_NP NVARCHAR(4)
        DECLARE @APP_WEB_FORCE_BRANCH_FP NVARCHAR(4)
        DECLARE @APP_WEB_FORCE_BRANCH_FC NVARCHAR(4)

        DECLARE @APP_WEB_CUSTOMER_COLOR NVARCHAR(20)
        DECLARE @APP_WEB_CUSTOMER_TITLE NVARCHAR(50)

        DECLARE @APP_WEB_VISTA_CARRITO_LISTA NVARCHAR(2)
        DECLARE @APP_WEB_VISTA_CARRITO_GRILLA NVARCHAR(2)

        DECLARE @APP_WEB_CART_PRESENTATION_AFTER_DESCRIPTION NVARCHAR(50)

        DECLARE @ML_USER_ID NVARCHAR(50)
        DECLARE @ML_CODE NVARCHAR(250)
        DECLARE @ML_ACCESS_TOKEN NVARCHAR(250)
        DECLARE @ML_REFRESH_TOKEN NVARCHAR(250)
        DECLARE @ML_EXPIRES_IN NVARCHAR(100)
        DECLARE @ML_LOGIN_TIME NVARCHAR(100)
        DECLARE @ML_APP_ID NVARCHAR(250)
        DECLARE @ML_CLIENT_SECRET NVARCHAR(250)
        DECLARE @ML_ENABLED NVARCHAR(10)


        SET @ML_APP_ID = (SELECT ISNULL(VALOR,'') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_ML_APP_ID')
        IF @ML_APP_ID IS NULL SET @ML_APP_ID = ''

        SET @ML_USER_ID = (SELECT ISNULL(VALOR,'') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_ML_USER_ID')
        IF @ML_USER_ID IS NULL SET @ML_USER_ID = ''

        SET @ML_CODE = (SELECT ISNULL(VALOR,'') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_ML_CODE')
        IF @ML_CODE IS NULL SET @ML_CODE = ''

        SET @ML_ACCESS_TOKEN = (SELECT ISNULL(VALOR,'') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_ML_ACCESS_TOKEN')
        IF @ML_ACCESS_TOKEN IS NULL SET @ML_ACCESS_TOKEN = ''

        SET @ML_REFRESH_TOKEN = (SELECT ISNULL(VALOR,'') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_ML_REFRESH_TOKEN')
        IF @ML_REFRESH_TOKEN IS NULL SET @ML_REFRESH_TOKEN = ''

        SET @ML_EXPIRES_IN = (SELECT ISNULL(VALOR,'') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_ML_EXPIRES_IN')
        IF @ML_EXPIRES_IN IS NULL SET @ML_EXPIRES_IN = ''

        SET @ML_LOGIN_TIME = (SELECT ISNULL(VALOR,'') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_ML_LOGIN_TIME')
        IF @ML_LOGIN_TIME IS NULL SET @ML_LOGIN_TIME = ''

        SET @ML_CLIENT_SECRET = (SELECT ISNULL(VALOR,'') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_ML_CLIENT_SECRET')
        IF @ML_CLIENT_SECRET IS NULL SET @ML_CLIENT_SECRET = ''

        SET @ML_ENABLED = (SELECT ISNULL(VALOR,'False') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_ML_ENABLED')
        IF @ML_ENABLED IS NULL SET @ML_ENABLED = 'False'
        
        SET @APP_WEB_CART_PRESENTATION_AFTER_DESCRIPTION = (SELECT ISNULL(VALOR,'NO') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_CART_PRESENTATION_AFTER_DESCRIPTION')
        IF @APP_WEB_CART_PRESENTATION_AFTER_DESCRIPTION IS NULL SET @APP_WEB_CART_PRESENTATION_AFTER_DESCRIPTION = 'NO'


        SET @APP_WEB_USA_SEMAFORO_STOCK = (SELECT ISNULL(VALOR,'NO') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_USA_SEMAFORO_STOCK')
        IF @APP_WEB_USA_SEMAFORO_STOCK IS NULL SET @APP_WEB_USA_SEMAFORO_STOCK = 'NO'

        -- STOCK NIVEL 1
        SET @APP_WEB_STOCK_1_COLOR = (SELECT ISNULL(VALOR,'#48BB5B') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_1_COLOR')
        IF @APP_WEB_STOCK_1_COLOR IS NULL SET @APP_WEB_STOCK_1_COLOR = '#48BB5B'

        SET @APP_WEB_STOCK_1_LEYENDA = (SELECT ISNULL(VALOR,'Stock Correcto') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_1_LEYENDA')
        IF @APP_WEB_STOCK_1_LEYENDA IS NULL SET @APP_WEB_STOCK_1_LEYENDA = 'Stock Correcto'

        SET @APP_WEB_STOCK_1_PORCENTAJE = (SELECT ISNULL(VALOR,'0') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_1_PORCENTAJE')
        IF @APP_WEB_STOCK_1_PORCENTAJE IS NULL SET @APP_WEB_STOCK_1_PORCENTAJE = '0'

        SET @APP_WEB_STOCK_1_CONDICION = (SELECT ISNULL(VALOR,'ABO') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_1_CONDICION')
        IF @APP_WEB_STOCK_1_CONDICION IS NULL SET @APP_WEB_STOCK_1_CONDICION = 'ABO'

        SET @APP_WEB_STOCK_1_TIPO_STOCK = (SELECT ISNULL(VALOR,'MAX') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_1_TIPO_STOCK')
        IF @APP_WEB_STOCK_1_TIPO_STOCK IS NULL SET @APP_WEB_STOCK_1_TIPO_STOCK = 'MAX'

        -- STOCK NIVEL 2
        SET @APP_WEB_STOCK_2_COLOR = (SELECT ISNULL(VALOR,'#E39215') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_2_COLOR')
        IF @APP_WEB_STOCK_2_COLOR IS NULL SET @APP_WEB_STOCK_2_COLOR = '#E39215'

        SET @APP_WEB_STOCK_2_LEYENDA = (SELECT ISNULL(VALOR,'Poco stock') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_2_LEYENDA')
        IF @APP_WEB_STOCK_2_LEYENDA IS NULL SET @APP_WEB_STOCK_2_LEYENDA = 'Poco stock'

        SET @APP_WEB_STOCK_2_PORCENTAJE = (SELECT ISNULL(VALOR,'50') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_2_PORCENTAJE')
        IF @APP_WEB_STOCK_2_PORCENTAJE IS NULL SET @APP_WEB_STOCK_2_PORCENTAJE = '50'

        SET @APP_WEB_STOCK_2_CONDICION = (SELECT ISNULL(VALOR,'UND') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_2_CONDICION')
        IF @APP_WEB_STOCK_2_CONDICION IS NULL SET @APP_WEB_STOCK_2_CONDICION = 'UND'

        SET @APP_WEB_STOCK_2_TIPO_STOCK = (SELECT ISNULL(VALOR,'MAX') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_2_TIPO_STOCK')
        IF @APP_WEB_STOCK_2_TIPO_STOCK IS NULL SET @APP_WEB_STOCK_2_TIPO_STOCK = 'MAX'

        -- STOCK NIVEL 3
        SET @APP_WEB_STOCK_3_COLOR = (SELECT ISNULL(VALOR,'#E32E15') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_3_COLOR')
        IF @APP_WEB_STOCK_3_COLOR IS NULL SET @APP_WEB_STOCK_3_COLOR = '#E32E15'

        SET @APP_WEB_STOCK_3_LEYENDA = (SELECT ISNULL(VALOR,'Consultar') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_3_LEYENDA')
        IF @APP_WEB_STOCK_3_LEYENDA IS NULL SET @APP_WEB_STOCK_3_LEYENDA = 'Consultar'

        SET @APP_WEB_STOCK_3_PORCENTAJE = (SELECT ISNULL(VALOR,'0') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_3_PORCENTAJE')
        IF @APP_WEB_STOCK_3_PORCENTAJE IS NULL SET @APP_WEB_STOCK_3_PORCENTAJE = '0'

        SET @APP_WEB_STOCK_3_CONDICION = (SELECT ISNULL(VALOR,'UND') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_3_CONDICION')
        IF @APP_WEB_STOCK_3_CONDICION IS NULL SET @APP_WEB_STOCK_3_CONDICION = 'UND'

        SET @APP_WEB_STOCK_3_TIPO_STOCK = (SELECT ISNULL(VALOR,'MIN') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_STOCK_3_TIPO_STOCK')
        IF @APP_WEB_STOCK_3_TIPO_STOCK IS NULL SET @APP_WEB_STOCK_3_TIPO_STOCK = 'MIN'

        SET @APP_WEB_COMENTARIOS_DASHBOARD = (SELECT ISNULL(VALORAUX,'') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_COMENTARIOS_DASHBOARD')
        IF @APP_WEB_COMENTARIOS_DASHBOARD IS NULL SET @APP_WEB_COMENTARIOS_DASHBOARD = ''

        SET @APP_WEB_TC_DEFAULT_CARRO = (SELECT ISNULL(VALOR,'NP') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_TC_DEFAULT_CARRO')
        IF @APP_WEB_TC_DEFAULT_CARRO IS NULL SET @APP_WEB_TC_DEFAULT_CARRO = 'NP'

        SET @APP_WEB_TC_DEFAULT_FACTURADOR = (SELECT ISNULL(VALOR,'NP') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_TC_DEFAULT_FACTURADOR')
        IF @APP_WEB_TC_DEFAULT_FACTURADOR IS NULL SET @APP_WEB_TC_DEFAULT_FACTURADOR = 'NP'

        SET @APP_WEB_TC_DEFAULT_FACTURADORG = (SELECT ISNULL(VALOR,'NP') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_TC_DEFAULT_FACTURADORG')
        IF @APP_WEB_TC_DEFAULT_FACTURADORG IS NULL SET @APP_WEB_TC_DEFAULT_FACTURADORG = 'NP'
        

        SET @APP_WEB_BRANCH_DEFAULT_NP = (SELECT ISNULL(VALOR,'') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_BRANCH_DEFAULT_NP')
        IF @APP_WEB_BRANCH_DEFAULT_NP IS NULL SET @APP_WEB_BRANCH_DEFAULT_NP = ''

        SET @APP_WEB_BRANCH_DEFAULT_FP = (SELECT ISNULL(VALOR,'') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_BRANCH_DEFAULT_FP')
        IF @APP_WEB_BRANCH_DEFAULT_FP IS NULL SET @APP_WEB_BRANCH_DEFAULT_FP = ''

        SET @APP_WEB_BRANCH_DEFAULT_FC = (SELECT ISNULL(VALOR,'') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_BRANCH_DEFAULT_FC')
        IF @APP_WEB_BRANCH_DEFAULT_FC IS NULL SET @APP_WEB_BRANCH_DEFAULT_FC = ''


        SET @APP_WEB_FORCE_BRANCH_NP = (SELECT ISNULL(VALOR,'NO') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_FORCE_BRANCH_NP')
        IF @APP_WEB_FORCE_BRANCH_NP IS NULL SET @APP_WEB_FORCE_BRANCH_NP = 'NO'

        SET @APP_WEB_FORCE_BRANCH_FP = (SELECT ISNULL(VALOR,'NO') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_FORCE_BRANCH_FP')
        IF @APP_WEB_FORCE_BRANCH_FP IS NULL SET @APP_WEB_FORCE_BRANCH_FP = 'NO'

        SET @APP_WEB_FORCE_BRANCH_FC = (SELECT ISNULL(VALOR,'NO') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_FORCE_BRANCH_FC')
        IF @APP_WEB_FORCE_BRANCH_FC IS NULL SET @APP_WEB_FORCE_BRANCH_FC = 'NO'

        SET @APP_WEB_VISTA_CARRITO_GRILLA = (SELECT ISNULL(VALOR,'NO') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_VISTA_CARRITO_GRILLA')
        IF @APP_WEB_VISTA_CARRITO_GRILLA IS NULL SET @APP_WEB_VISTA_CARRITO_GRILLA = 'NO'

        SET @APP_WEB_VISTA_CARRITO_LISTA = (SELECT ISNULL(VALOR,'NO') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_VISTA_CARRITO_LISTA')
        IF @APP_WEB_VISTA_CARRITO_LISTA IS NULL SET @APP_WEB_VISTA_CARRITO_LISTA = 'NO'


        SET @APP_WEB_CUSTOMER_COLOR = (SELECT ISNULL(VALOR,'#4b88c6') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_CUSTOMER_COLOR')
        IF @APP_WEB_CUSTOMER_COLOR IS NULL SET @APP_WEB_CUSTOMER_COLOR = '#4b88c6'

        SET @APP_WEB_CUSTOMER_TITLE = (SELECT ISNULL(VALOR,'Bienvenido') FROM TA_CONFIGURACION WHERE CLAVE = 'APP_WEB_CUSTOMER_TITLE')
        IF @APP_WEB_CUSTOMER_TITLE IS NULL SET @APP_WEB_CUSTOMER_TITLE = 'Bienvenido'

        SELECT 'APP_WEB_ML_APP_ID' as clave,@ML_APP_ID as valor
        UNION 
        SELECT 'APP_WEB_ML_USER_ID' as clave,@ML_USER_ID as valor
        UNION 
        SELECT 'APP_WEB_ML_CODE' as clave,@ML_CODE as valor
        UNION 
        SELECT 'APP_WEB_ML_ACCESS_TOKEN' as clave, @ML_ACCESS_TOKEN as valor
        UNION 
        SELECT 'APP_WEB_ML_REFRESH_TOKEN' as clave, @ML_REFRESH_TOKEN as valor
        UNION 
        SELECT 'APP_WEB_ML_EXPIRES_IN' as clave, @ML_EXPIRES_IN as valor
        UNION 
        SELECT 'APP_WEB_ML_LOGIN_TIME' as clave, @ML_LOGIN_TIME as valor
        UNION
        SELECT 'APP_WEB_ML_CLIENT_SECRET' as clave, @ML_CLIENT_SECRET as valor
        UNION 
        SELECT 'APP_WEB_ML_ENABLED' as clave, @ML_ENABLED as valor
        
        UNION
        SELECT 'APP_WEB_USA_SEMAFORO_STOCK' as clave, @APP_WEB_USA_SEMAFORO_STOCK as valor
        UNION
        SELECT 'APP_WEB_STOCK_1_COLOR' AS clave,@APP_WEB_STOCK_1_COLOR as valor
        UNION
        SELECT 'APP_WEB_STOCK_1_LEYENDA' AS clave,@APP_WEB_STOCK_1_LEYENDA as valor
        UNION
        SELECT 'APP_WEB_STOCK_1_PORCENTAJE' AS clave,@APP_WEB_STOCK_1_PORCENTAJE as valor
        UNION
        SELECT 'APP_WEB_STOCK_1_CONDICION' AS clave,@APP_WEB_STOCK_1_CONDICION as valor
        UNION
        SELECT 'APP_WEB_STOCK_1_TIPO_STOCK' AS clave,@APP_WEB_STOCK_1_TIPO_STOCK as valor
        UNION
        SELECT 'APP_WEB_STOCK_2_COLOR' AS clave,@APP_WEB_STOCK_2_COLOR as valor
        UNION
        SELECT 'APP_WEB_STOCK_2_LEYENDA' AS clave,@APP_WEB_STOCK_2_LEYENDA as valor
        UNION
        SELECT 'APP_WEB_STOCK_2_PORCENTAJE' AS clave,@APP_WEB_STOCK_2_PORCENTAJE as valor
        UNION
        SELECT 'APP_WEB_STOCK_2_CONDICION' AS clave,@APP_WEB_STOCK_2_CONDICION as valor
        UNION
        SELECT 'APP_WEB_STOCK_2_TIPO_STOCK' AS clave,@APP_WEB_STOCK_2_TIPO_STOCK as valor
        UNION
        SELECT 'APP_WEB_STOCK_3_COLOR' AS clave,@APP_WEB_STOCK_3_COLOR as valor
        UNION
        SELECT 'APP_WEB_STOCK_3_LEYENDA' AS clave,@APP_WEB_STOCK_3_LEYENDA as valor
        UNION
        SELECT 'APP_WEB_STOCK_3_PORCENTAJE' AS clave,@APP_WEB_STOCK_3_PORCENTAJE as valor
        UNION
        SELECT 'APP_WEB_STOCK_3_CONDICION' AS clave,@APP_WEB_STOCK_3_CONDICION as valor
        UNION
        SELECT 'APP_WEB_STOCK_3_TIPO_STOCK' AS clave,@APP_WEB_STOCK_3_TIPO_STOCK as valor
        UNION
        SELECT 'APP_WEB_COMENTARIOS_DASHBOARD' AS clave,@APP_WEB_COMENTARIOS_DASHBOARD as valor
        UNION
        SELECT 'APP_WEB_TC_DEFAULT_CARRO' AS clave,@APP_WEB_TC_DEFAULT_CARRO as valor
        UNION
        SELECT 'APP_WEB_TC_DEFAULT_FACTURADOR' AS clave,@APP_WEB_TC_DEFAULT_FACTURADOR as valor
        UNION
        SELECT 'APP_WEB_TC_DEFAULT_FACTURADORG' AS clave,@APP_WEB_TC_DEFAULT_FACTURADORG as valor
        
        UNION
        SELECT 'APP_WEB_BRANCH_DEFAULT_NP' AS clave,@APP_WEB_BRANCH_DEFAULT_NP as valor
        UNION
        SELECT 'APP_WEB_BRANCH_DEFAULT_FP' AS clave,@APP_WEB_BRANCH_DEFAULT_FP as valor
        UNION
        SELECT 'APP_WEB_BRANCH_DEFAULT_FC' AS clave,@APP_WEB_BRANCH_DEFAULT_FC as valor
        
        UNION
        SELECT 'APP_WEB_FORCE_BRANCH_NP' AS clave,@APP_WEB_FORCE_BRANCH_NP as valor
        UNION
        SELECT 'APP_WEB_FORCE_BRANCH_FP' AS clave,@APP_WEB_FORCE_BRANCH_FP as valor
        UNION
        SELECT 'APP_WEB_FORCE_BRANCH_FC' AS clave,@APP_WEB_FORCE_BRANCH_FC as valor


        UNION
        SELECT 'APP_WEB_CUSTOMER_COLOR' AS clave,@APP_WEB_CUSTOMER_COLOR as valor
        UNION
        SELECT 'APP_WEB_CUSTOMER_TITLE' AS clave,@APP_WEB_CUSTOMER_TITLE as valor

        UNION
        SELECT 'APP_WEB_VISTA_CARRITO_LISTA' AS clave,@APP_WEB_VISTA_CARRITO_LISTA as valor
        UNION
        SELECT 'APP_WEB_VISTA_CARRITO_GRILLA' AS clave,@APP_WEB_VISTA_CARRITO_GRILLA as valor

        UNION
        SELECT 'APP_WEB_CART_PRESENTATION_AFTER_DESCRIPTION' as clave,@APP_WEB_CART_PRESENTATION_AFTER_DESCRIPTION as valor
        """