
GO

/****** Object:  UserDefinedFunction [dbo].[FN_OBTENER_ULTIMA_FECHA_COTIZACION]    Script Date: 05/04/2023 11:54:33 ******/
DROP FUNCTION [dbo].[FN_OBTENER_ULTIMA_FECHA_COTIZACION]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_OBTENER_ULTIMA_FECHA_COTIZACION]    Script Date: 05/04/2023 11:54:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FN_OBTENER_ULTIMA_FECHA_COTIZACION] (@MONEDA VARCHAR(4))  
RETURNS DATETIME 
AS  
BEGIN 

DECLARE @MONEDA1 MONEY
DECLARE @MONEDA2 MONEY
DECLARE @MONEDA3 MONEY
DECLARE @MONEDA4 MONEY
DECLARE @MONEDA5 MONEY
DECLARE @MONEDA1_ANT MONEY
DECLARE @MONEDA2_ANT MONEY
DECLARE @MONEDA3_ANT MONEY
DECLARE @MONEDA4_ANT MONEY
DECLARE @MONEDA5_ANT MONEY
DECLARE @FECHA_ANT DATETIME
DECLARE @FECHA DATETIME

DECLARE CRS02 CURSOR FOR
SELECT  FECHA_HORA,MONEDA2,MONEDA3,MONEDA4,MONEDA5  FROM TA_COTIZACION ORDER BY FECHA_HORA desc
OPEN CRS02 
FETCH NEXT FROM CRS02 INTO @FECHA, @MONEDA2,@MONEDA3, @MONEDA4, @MONEDA5 
WHILE @@FETCH_STATUS = 0
BEGIN
  IF LTRIM(@MONEDA) = '2'
	IF @MONEDA2 <> @MONEDA2_ANT AND NOT @MONEDA2_ANT IS NULL
		BEGIN
		   GOTO SALIR 
		END   

  IF LTRIM(@MONEDA) = '3'
	IF @MONEDA3 <> @MONEDA3_ANT AND NOT @MONEDA3_ANT IS NULL
		BEGIN
		   GOTO SALIR 
		END  

  IF LTRIM(@MONEDA) = '4'
	IF @MONEDA4 <> @MONEDA4_ANT AND NOT @MONEDA4_ANT IS NULL
		BEGIN
		   GOTO SALIR 
		END 

  IF LTRIM(@MONEDA) = '5'
	IF @MONEDA5 <> @MONEDA5_ANT AND NOT @MONEDA5_ANT IS NULL
		BEGIN
		   GOTO SALIR 
		END 

  SET @MONEDA2_ANT = @MONEDA2
  SET @MONEDA3_ANT = @MONEDA3
  SET @MONEDA4_ANT = @MONEDA4
  SET @MONEDA5_ANT = @MONEDA5
  SET @FECHA_ANT = @FECHA


 FETCH NEXT FROM CRS02 INTO @FECHA, @MONEDA2, @MONEDA3, @MONEDA4, @MONEDA5
END


SALIR:
CLOSE CRS02
DEALLOCATE CRS02
RETURN @FECHA_ANT
END
GO


