
GO

/****** Object:  UserDefinedFunction [dbo].[FN_PRECIO_LISTA]    Script Date: 12/08/2022 10:54:52 ******/
DROP FUNCTION [dbo].[FN_PRECIO_LISTA]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_PRECIO_LISTA]    Script Date: 12/08/2022 10:54:52 ******/
SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER OFF
GO

CREATE FUNCTION [dbo].[FN_PRECIO_LISTA] (@idarticulo NVARCHAR(25), @idlista NVARCHAR(4), @clase NVARCHAR(4))  
RETURNS MONEY AS  
BEGIN

	DECLARE @MONEDA NVARCHAR(4)
	DECLARE @cotiz MONEY
	DECLARE @cotiz2 MONEY
	DECLARE @cotiz3 MONEY
	DECLARE @cotiz4 MONEY
	DECLARE @cotiz5 MONEY
	DECLARE @precio MONEY
	DECLARE @importeFinal MONEY

	SET @MONEDA = (SELECT LTRIM(ISNULL(MONEDA,'1')) FROM V_MA_ARTICULOS WHERE LTRIM(IDARTICULO)=LTRIM(@idarticulo))

	SET @cotiz = ISNULL((SELECT ISNULL(MONEDA1,1) FROM TA_COTIZACION WHERE FECHA_HORA = CONVERT(date,GETDATE())),1)
	SET @cotiz2 = ISNULL((SELECT ISNULL(MONEDA2,1) FROM TA_COTIZACION WHERE FECHA_HORA = CONVERT(date,GETDATE())),1)
	SET @cotiz3 = ISNULL((SELECT ISNULL(MONEDA3,1) FROM TA_COTIZACION WHERE FECHA_HORA = CONVERT(date,GETDATE())),1)
	SET @cotiz4 = ISNULL((SELECT ISNULL(MONEDA4,1) FROM TA_COTIZACION WHERE FECHA_HORA = CONVERT(date,GETDATE())),1)
	SET @cotiz5 = ISNULL((SELECT ISNULL(MONEDA5,1) FROM TA_COTIZACION WHERE FECHA_HORA = CONVERT(date,GETDATE())),1)

	IF LTRIM(@clase) = '1'
		SET @precio = (SELECT PRECIO1 FROM V_MA_PRECIOS WHERE LTRIM(IDLISTA)=LTRIM(@idlista) AND LTRIM(IDARTICULO)=LTRIM(@idarticulo))
	IF LTRIM(@clase) = '2'
		SET @precio = (SELECT PRECIO2 FROM V_MA_PRECIOS WHERE LTRIM(IDLISTA)=LTRIM(@idlista) AND LTRIM(IDARTICULO)=LTRIM(@idarticulo))
	IF LTRIM(@clase) = '3'
		SET @precio = (SELECT PRECIO3 FROM V_MA_PRECIOS WHERE LTRIM(IDLISTA)=LTRIM(@idlista) AND LTRIM(IDARTICULO)=LTRIM(@idarticulo))
	IF LTRIM(@clase) = '4'
		SET @precio = (SELECT PRECIO4 FROM V_MA_PRECIOS WHERE LTRIM(IDLISTA)=LTRIM(@idlista) AND LTRIM(IDARTICULO)=LTRIM(@idarticulo))
	IF LTRIM(@clase) = '5'
		SET @precio = (SELECT PRECIO5 FROM V_MA_PRECIOS WHERE LTRIM(IDLISTA)=LTRIM(@idlista) AND LTRIM(IDARTICULO)=LTRIM(@idarticulo))
	IF LTRIM(@clase) = '6'
		SET @precio = (SELECT PRECIO6 FROM V_MA_PRECIOS WHERE LTRIM(IDLISTA)=LTRIM(@idlista) AND LTRIM(IDARTICULO)=LTRIM(@idarticulo))
	IF LTRIM(@clase) = '7'
		SET @precio = (SELECT PRECIO7 FROM V_MA_PRECIOS WHERE LTRIM(IDLISTA)=LTRIM(@idlista) AND LTRIM(IDARTICULO)=LTRIM(@idarticulo))
	IF LTRIM(@clase) = '8'
		SET @precio = (SELECT PRECIO8 FROM V_MA_PRECIOS WHERE LTRIM(IDLISTA)=LTRIM(@idlista) AND LTRIM(IDARTICULO)=LTRIM(@idarticulo))

	IF @MONEDA = '1'
		SET @importeFinal = @precio

	IF @MONEDA = '2'
		SET @importeFinal = @precio * @cotiz2

	IF @MONEDA = '3'
		SET @importeFinal = @precio * @cotiz3

	IF @MONEDA = '4'
		SET @importeFinal = @precio * @cotiz4

	IF @MONEDA = '5'
		SET @importeFinal = @precio * @cotiz5

	RETURN @importeFinal 		
END
GO


