
GO

/****** Object:  StoredProcedure [dbo].[sp_web_setRemitoTransporte]    Script Date: 13/06/2022 16:43:11 ******/
DROP PROCEDURE [dbo].[sp_web_setRemitoTransporte]
GO

/****** Object:  StoredProcedure [dbo].[sp_web_setRemitoTransporte]    Script Date: 13/06/2022 16:43:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[sp_web_setRemitoTransporte]
	@cliente nvarchar(4),
	@nroViaje nvarchar(13),
	@estado nvarchar(4),
	@obs NVARCHAR(100)
AS
BEGIN
	
	SET NOCOUNT ON;
	DECLARE @WHERE NVARCHAR(250)
	DECLARE @rs NVARCHAR(MAX)
	DECLARE @BASETTE NVARCHAR(250)

	DECLARE @SUCURSAL NVARCHAR(4)
	DECLARE @NUMERO NVARCHAR(8)
	DECLARE @TMPNUMERO NVARCHAR(8)
	DECLARE @LETRA NVARCHAR(1)

	DECLARE @fecha NVARCHAR(10)
	DECLARE @TC NVARCHAR(2)

	SET @TC = 'RM'
	SET @fecha = CONVERT(NVARCHAR(10),GETDATE(),103)
	SET @SUCURSAL = '0001'
	SET @LETRA='R'

	--SET @BASETTE = (SELECT VALOR FROM TA_CONFIGURACION WHERE CLAVE='SAT_BASEDEDATOS')

	SELECT @TMPNUMERO = MAX(NUMERO_DOCUMENTO) + 1 FROM MV_RUTEOCAB
	WHERE TIPO_DOCUMENTO = @TC AND DOCUMENTO_SUCURSAL=@SUCURSAL AND DOCUMENTO_LETRA=@LETRA

	SET @NUMERO = REPLICATE(' ',8 - LEN(@TMPNUMERO)) + @TMPNUMERO
    SET @NUMERO = REPLACE(@NUMERO,' ','0')

	IF @estado <> ''
		SET @estado = REPLICATE(' ',4 - LEN(@estado)) + @estado


	INSERT INTO MV_RUTEOCAB 
	(CLIENTE,ORDEN_DE_CARGA,NRO_VIAJE,FECHA_PROCESO,TIPO_DOCUMENTO,DOCUMENTO_SUCURSAL,NUMERO_DOCUMENTO,DOCUMENTO_LETRA,
	NRO_SALIDA,CODIGO_CLIENTE,SUCURSAL_CLIENTE,NOMBRE_CLIENTE,DOMICILIO,CODIGO_ESTADO)
	VALUES (@cliente,1,@nroViaje,@fecha,'RM',@SUCURSAL, @NUMERO,@LETRA,1,Null,null,'',null,@estado)

	DECLARE @ID INT

	SELECT @ID = id FROM MV_RUTEOCAB WHERE TIPO_DOCUMENTO=@TC AND DOCUMENTO_SUCURSAL = @SUCURSAL AND NUMERO_DOCUMENTO = @NUMERO AND DOCUMENTO_LETRA=@LETRA
	
	DECLARE @TIPOESTADO NVARCHAR(1)
	DECLARE @FECHAENT NVARCHAR(16)
	
	SET @TIPOESTADO = (SELECT LTRIM(TIPO) FROM TA_ESTADOS WHERE LTRIM(CODIGO)=LTRIM(@estado))
	IF @TIPOESTADO = 'O' SET @TIPOESTADO = ''''
	
	IF @TIPOESTADO = 'P' OR @TIPOESTADO = 'E'
		SET @FECHAENT = GETDATE() 
	ELSE
		SET @FECHAENT = NULL
	
	INSERT INTO MV_SEGUIMIENTO (CLIENTE,NRO_VIAJE,TIPO_DOCUMENTO,NRO_COMPROBANTE,NRO_SALIDA,FECHA_HORA,COD_NOVEDAD,OBSERVACION)
	VALUES (@cliente,@nroViaje,@TC,@SUCURSAL + @NUMERO + @LETRA,1,CAST(GETDATE() AS date), @estado, @obs)
	
	
	UPDATE MV_RUTEOCAB 
	SET Devolucion=@TIPOESTADO,
	PE='1',PEDEV='0',
	DEV_PESO_BRUTO=0,DEV_BULTOS=0,DEV_M3=0,DEV_VD=0,DEV_CR=0,FH_ENT_DESTINO=@FECHAENT
	WHERE ID= @ID

END







GO


