
GO

/****** Object:  Trigger [TRG_ValidaFPEF]    Script Date: 04/19/2022 19:03:55 ******/
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[TRG_ValidaFPEF]'))
DROP TRIGGER [dbo].[TRG_ValidaFPEF]
GO

GO

/****** Object:  Trigger [dbo].[TRG_ValidaFPEF]    Script Date: 04/19/2022 19:03:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE TRIGGER [dbo].[TRG_ValidaFPEF] ON [dbo].[MV_ASIENTOS]
FOR INSERT, UPDATE
AS
DECLARE @DBID INT
DECLARE @DBNAME NVARCHAR(128)
SET @DBID = DB_ID()
SET @DBNAME = DB_NAME()
    DECLARE @TC NVARCHAR(4)
    DECLARE @CODIGO NVARCHAR(15)
    DECLARE @MEDIODEPAGO AS NVARCHAR(2)
    DECLARE CRS_MV_ASIENTOS CURSOR FOR  SELECT Cuenta,TC FROM Inserted
    OPEN CRS_MV_ASIENTOS
    FETCH NEXT FROM CRS_MV_ASIENTOS INTO @CODIGO,@TC
    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF @TC='CBFP'
            BEGIN
                SELECT @MEDIODEPAGO  =  MEDIOdePAGO FROM MA_CUENTAS WHERE CODIGO =@CODIGO
                IF (@MEDIODEPAGO<>'EF' AND @MEDIODEPAGO <>'')
                    BEGIN
                       ROLLBACK TRANSACTION
                       RAISERROR   ('SOLO PUEDE UTILIZAR EFECTIVO COMO MEDIO DE PAGO PARA ESTE COMPROBANTE',    16, 1, @DBID,  @DBNAME)
                         GoTo FIN
                      End
            End
        FETCH NEXT FROM CRS_MV_ASIENTOS INTO @CODIGO,@TC
     End
FIN:
Close CRS_MV_ASIENTOS
 DEALLOCATE CRS_MV_ASIENTOS
GO


